### ISSUE TITLE
Number of GPUs used for training and training time

### ISSUE THREAD

**Issue by Shuntw6096** [basiclab/DA-OD-MEAA-PyTorch#1]
Hi, 
I would like to ask the number of GPUs used for training and the training time.
Thanks.

**Comment by erictseng610** [comment]
We use a single GPU for training.
With GTX 1080, for each 100 iter, the training time is about 60 seconds
![train](https://user-images.githubusercontent.com/48157192/113665382-f8bde500-96df-11eb-9590-6a72505bb975.png)

**Comment by Shuntw6096** [comment]
Thanks for your reply.
