### ISSUE TITLE
lib/model/nms/src/nms_cuda.c: No such file or directory

### ISSUE THREAD

**Issue by Shuntw6096** [basiclab/DA-OD-MEAA-PyTorch#3]
It seems that nms_cuda.c are missing. I encountered this problem when I compile code.
I follow this [https://github.com/jwyang/fpn.pytorch/issues/1](https://github.com/jwyang/fpn.pytorch/issues/1).

Thanks

**Comment by erictseng610** [comment]
Oh, it seems that  the nms_cuda.c are missing in previous git add file.

I have uploaded nms_cuda.c.
